### ISSUE TITLE
Simplify functions in StateEEIOFigures.R (dev)

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO-State#10]
The functions are overly complex.

Most functions called _prepareDFforFigure_ which is far too complex itself, operating on too many objects of different natures. It performs a _calculateEEIOModel_.

_stackedBarChartResult_  alone calls _prepareDFforFigure_ for each model 3 times using different parameters. 

Overall it is much clearer if a function operates on a single model like most of useeior calculation and graphing functions. 
Also the actual result calculated becomes very obscure in these wrapped functions.

**Comment by WesIngwersen** [comment]
for calculation functions - we can just design them for a single model and then use _lapply()_ to run them over a list rather than sending lists of models.

**Comment by WesIngwersen** [comment]
Separate out the result calls from the graphing functions to be clearer and then allow the graphing functions to operate on a result directly rather than on models

**Comment by bl-young** [comment]
To be clear - are you looking at the module as it is on develop? I've been attempting to simplify things in the results branch, though certainly there is more room to improve still there.

**Comment by WesIngwersen** [comment]
> To be clear - are you looking at the module as it is on develop? I've been attempting to simplify things in the results branch, though certainly there is more room to improve still there.

I was looking in dev; thanks i can see results

**Comment by WesIngwersen** [comment]
initial refactoring complete as of 10193aefb5508dfa4df29d0bb230f2909bcda070
