### ISSUE TITLE
calculateCBETradeBalance likely double-counting

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO-State#16]
The current approach is treating RoW and RoUS distinctly and the inconsistency is likely not valid

**Comment by WesIngwersen** [comment]
New methods described [here](https://github.com/USEPA/StateCBEIdocs/commit/06b5d8252c4b7807170e025a01534eed14b4fd19)

**Comment by bl-young** [comment]
@WesIngwersen, with revised calc in commit above, new CBEI figure looks like:
![cbe_trade](https://github.com/user-attachments/assets/b592d91f-0eff-4ce4-9705-c33051b69427)
