### ISSUE TITLE
install_useeior() without pak requires mirror to be setup in user's R 

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO-State#22]
````                                                                    
processing file: CalculateStateCBE.Rmd                                           
Error in `contrib.url()`:
! trying to use CRAN without setting a mirror
Backtrace:
 1. global install_useeior()
 2. utils::install.packages("pak")
 3. utils::contrib.url(repos, "source")
 ```

occurred for me when running
https://github.com/USEPA/USEEIO-State/blob/b5f0cc5a9218fdd30cbfcf3aab80520cd7a7e6a8/examples/CalculateStateCBE.Rmd#L33

**Comment by WesIngwersen** [comment]
for more info, in my RStudio, under Global Options and Packages, i have `Global (CDN) - RStudio` set as the primary CRAN repository which was a default with installation. Since it's here, I'm suprised to get the error.  A fix could entail getting the users default CRAN repository if that's possible, or just setting one like this one.

**Comment by bl-young** [comment]
From this post seems as though setting the repo within `install.packages` should do the trick https://stackoverflow.com/a/33970452

**Comment by bl-young** [comment]
setting the mirror seems to solve the issue locally but was causing errors in the action with the installation of pak. so in https://github.com/USEPA/USEEIO-State/commit/28e44972266e43ac1f45687a7e0e6557247f63b6 I added pak installation directly in the runner.

I was able to uninstall pak and useeior and render the doc successfully locally, and its working on the runner. @WesIngwersen could you confirm on your end as well?
