### ISSUE TITLE
StateCBE.Rmd - Support HTML and .docx output using same fig/caption and cross-references

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO-State#29]
Officedown is currently used to customize Word output.  But Word output is still less sharp and doesn't add natural section header, etc formatting so HTML is superior in this respect.  Bookdown can be used to provide the same syntax to enable figure and table captions, cross-references, etc for generating both outputs.

**Comment by ericmbell1** [comment]
Test comment
