### ISSUE TITLE
Add modelspecs for custom GHG VT and NY models

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO-State#9]
Per pattern they should go in VT and NY folders and have the name  EEIOv1.1-GHGc  in their modelstub

**Comment by bl-young** [comment]
VT added with https://github.com/USEPA/USEEIO-State/commit/44b87723bfcdb8954c6cefc2b4d4629da931bcac

**Comment by bl-young** [comment]
NY added with https://github.com/USEPA/USEEIO-State/commit/76061987b7971d2c5ac2eeb4fa2de4452435c30c
